* Grouping Selectors

First we tangle =index.html= with the original contents.

#+begin_quote
[...] be sure you add the class attribute in the HTML file.
#+end_quote

Then we add a class for each element.

[[file:index.html][index.html]] ≡

#+begin_src html :tangle index.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Grouping Selectors</title>
    <link rel="stylesheet" href="style.css">
  </head>
  <body>
    <button class="click-me">Click Me!</button>
    <button class="no-click-me">No, Click Me!</button>
  </body>
</html>
#+end_src

Now let's add prepare =style.css= to receive the declaration blocks.

[[file:style.css][style.css]] ≡

#+begin_src css :tangle style.css
<<declaration blocks>>
#+end_src

Then we add one declaration for each element's class.

~<<declaration blocks>> +≡~

#+begin_src css :noweb-ref declaration blocks
.click-me {
  <<click-me declarations>>
}

.no-click-me {
  <<no-click-me declarations>>
}
#+end_src

Now we add the properties that are specific to each element.

#+begin_quote
- *The first element*: a black background and white text
#+end_quote

For this color (and all the others):

#+begin_quote
[...] the format of any colors is entirely up to you; we trust you'll practice using the different values!
#+end_quote

Let's start with HEX and ~rgb()~.

~<<click-me declarations>> +≡~

#+begin_src css :noweb-ref click-me declarations
background-color: #000000;
color: rgb(255 255 255);
#+end_src

#+begin_quote
- *The second element*: a yellow background
#+end_quote

Let's use HSL for this one: yellow is obtained with:
- Hue: 60
- Saturation: 100%
- Lighting: 50%


~<<no-click-me declarations>> +≡~

#+begin_src css :noweb-ref no-click-me declarations
background-color: hsl(60 100% 50%);
#+end_src

Now, for the shared properties.

#+begin_quote
- *Both elements*: a font size of 28px and a list of fonts containing =Helvetica= and =Times New Roman=, with =sans-serif= as a fallback
#+end_quote

As the title of the assignment suggests, we'll use *grouping* for that.
To use grouping for the selectors in a CSS declaration block, we use all the grouped selectors, separated by commas.

~<<declaration blocks>> +≡~

#+begin_src css :noweb-ref declaration blocks
.click-me,
.no-click-me {
  font-size: 28px;
  font-family: Helvetica, "Times New Roman", sans-serif;
}
#+end_src
