# -*- auto-fill-function: nil; eval: (add-hook 'after-save-hook 'org-babel-tangle nil t); -*-

* Methods for Adding CSS
First, the assignment rules:

#+begin_quote
1. Only *type* selectors, and
2. Only *named* colors.
#+end_quote

First properties to add:

#+begin_quote
- =div=:
  - a red background,
  - white text,
  - a font size of 32px,
  - center aligned, and
  - bold.
#+end_quote

The element in question is:
#+begin_src html
<div>Style me via the external method!</div>
#+end_src

As it should use the /external/ method, we'll have to tangle a new CSS file.
There will only be one declaration block there.
We follow the rule and use a *type* selector, in this case for the ~div~ element.

[[file:style.css][style.css]] ≡

#+begin_src css :tangle style.css
div {
  <<External Declarations>>
}
#+end_src

As we'll need to link =style.css= on =index.html=, let's tangle it here, with the original content plus our necessary additions.
Let's link =style.css= there.

[[file:index.html][index.html]] ≡

#+begin_src html :tangle index.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="style.css">
    <style>
    <<Internal Declarations>>
    </style>
    <title>Methods for Adding CSS</title>
  </head>
  <body>
    <div>Style me via the external method!</div>
    <p>I would like to be styled with the internal method, please.</p>
    <<Button>>
  </body>
</html>
#+end_src

Now we add the required CSS declarations.

~<<External Declarations>> +≡~

#+begin_src css :noweb-ref External Declarations
background-color:red;
color:white;
font-size:32px;
text-align:center;
font-weight:bold;
#+end_src

The next style is to be applied to the ~p~ element.

#+begin_quote
- =p=:
  - a green background,
  - white text, and
  - a font size of 18px.
#+end_quote

This one has to be done with the /internal/ method.
Let's add the ~style~ element to =index.html='s ~head~.
Then we add the CSS declaration block for the element type we need to style, in this case ~p~.

~<<Internal Declarations>> +≡~

#+begin_src css :noweb-ref Internal Declarations
p {
  background-color:green;
  color:white;
  font-size:18px;
}
#+end_src

Finally, we style the ~button~ element.

#+begin_quote
- =button=:
  - an orange background and
  - a font size of 18px.
#+end_quote

As the styling for the button will be /inline/, we bring the element here.
Then we add the ~style~ /attributte/ for the element, with the appropriate declarations.

~<<Button>> +≡~

#+begin_src html :noweb-ref Button
<button style="background-color:orange; font-size=18px;">Inline Method</button>
#+end_src
