* CSS Methods

The rules of this assignment:

#+begin_quote
You can edit the CSS file by adding, removing, or editing selectors for a declaration block, or by moving declaration blocks around.
#+end_quote

#+begin_quote
*You should not edit the HTML file or any of the actual styles in the CSS*.
#+end_quote

Let's start with the /buttons/.
First the *Confirm* one.

From =index.html=:

#+begin_src html
<button id="confirm-button" class="button confirm">Confirm</button>
#+end_src

From =style.css=, the rules applied to *Confirm* are, in order:

#+begin_src css
body {
  font-family: Arial, Helvetica, sans-serif;
}

.confirm {
  background: green;
  color: white;
  font-weight: bold;
}

.button {
  background-color: rgb(255, 255, 255);
  color: rgb(0, 0, 0);
  font-size: 20px;
}
#+end_src

Let's analyze the resolution of those rules.
As they have the same priority---both selectors are /classes/---the *last defined* rule is applied.
This is why *Confirm* does not get a green background, as it should.
This is fixed by swapping those declaration blocks.

Let's take a look at the element for the second paragraph.

#+begin_src html
<p class="para small-para">I'm a smaller paragraph, also with extra bold text!</p>
#+end_src

The rules currently applied are, in order:

#+begin_src css
body {
  font-family: Arial, Helvetica, sans-serif;
}

.para,
.small-para {
  color: hsl(0, 0%, 0%);
  font-weight: 800;
}

.small-para {
  font-size: 14px;
  font-weight: 800;
}

.para {
  font-size: 22px;
}
#+end_src

The two rules controlling font size both have *classes* as descriptors.
Again, the last defined one is applied, and we have to swap them to fix the problem.

Now, the last paragraph:

#+begin_src html
<div class="text">I'm a div with thin text and a child div!
  <div class="text child">I'm a smaller child div with extra bold text.</div>
</div>
#+end_src

Let's just reorganize without changing anything, for clarity:

#+begin_src html
<div class="text">
  I'm a div with thin text and a child div!
  <div class="text child">
    I'm a smaller child div with extra bold text.
  </div>
</div>
#+end_src

The currently applied rules are, in order:

#+begin_src css
body {
  font-family: Arial, Helvetica, sans-serif;
}

.child {
  color: rgb(0, 0, 0);
  font-weight: 800;
  font-size: 14px;
}

div.text {
  color: rgb(0, 0, 0);
  font-size: 22px;
  font-weight: 100;
}
#+end_src

In this case, we have the selectors:
1. ~div.text~: *class + type*
2. ~.child~: *class*

The first selector /div.text/ has higher priority.
We could fix it by giving an even higher priority to the appropriate rule.
This could be done by chaining it with another class, ~text~.

#+begin_src css
.text.child {
  color: rgb(0, 0, 0);
  font-weight: 800;
  font-size: 14px;
}

div.text {
  color: rgb(0, 0, 0);
  font-size: 22px;
  font-weight: 100;
}
#+end_src
